<Project>

  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)StrongNamedAssemblyKey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileFullPath)" Link="Props\$(MSBuildThisFile)" />
  </ItemGroup>

</Project>
