<Project>

  <PropertyGroup>
    <AssemblyName>MathConverter.UnitTests</AssemblyName>
    <RootNamespace>HexInnovation.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileFullPath)" Link="Props\$(MSBuildThisFile)" />
    <Compile Include="$(MSBuildThisFileDirectory)..\..\CSharp\UnitTests\**\*.cs" Link="src\%(RecursiveDir)%(FileName)%(Extension)" />
  </ItemGroup>

  <Import Project="$(MSBuildThisFileDirectory)Common.props" />

</Project>
