<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>MathConverter.UnitTests</AssemblyName>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <UseMaui>true</UseMaui>
    <DefineConstants>XUNIT;MAUI</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App\MathConverter.Maui.csproj" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.31" />
  </ItemGroup>

  <Import Project="..\..\Common\UnitTests.props" />

  <PropertyGroup>
    <RootNamespace>HexInnovation.UnitTests</RootNamespace>
  </PropertyGroup>
</Project>
